export const CREATE_BOARD = 'CREATE_BOARD'
export const SET_CURRENT_BOARD = 'SET_CURRENT_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'

export const SET_ALERT = 'SET_ALERT'
export const UNSET_ALERT = 'UNSET_ALERT'

export const CHANGE_BOARD_PROPS = 'CHANGE_BOARD_PROPS'

export const CREATE_NEW_LIST = 'CREATE_NEW_LIST'
export const CHANGE_LIST_PROPS = 'CHANGE_LIST_PROPS'
export const DELETE_LIST = 'DELETE_LIST'
export const UPDATE_LISTS = 'UPDATE_LISTS'

export const CREATE_NEW_ITEM = 'CREATE_NEW_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const CHANGE_ITEM_PROPS = 'CHANGE_ITEM_PROPS'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'

export const SET_AUTH = 'SET_AUTH'
export const SET_REGISTER_STATUS = 'SET_REGISTER_STATUS'

export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
